apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: squash
  name: squash
spec:
  template:
    metadata:
      labels:
        app: squash
    spec:
      # hostPID: true
      containers:
      - name: squash
        image: soloio/squash:dev
        volumeMounts:
        - mountPath: /var/run/cri.sock
          name: crisock
        securityContext:
          privileged: true
        ports:
        - containerPort: 1234
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST_ADDR
          value: "$(POD_NAME).$(POD_NAMESPACE)"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: crisock
        hostPath:
          path: /var/run/dockershim.sock
