site_name: Squash
nav:
- Index: index.md
- CLI reference:
  - root: cli/squashctl.md
  - completion: cli/squashctl_completion.md
  - deploy: cli/squashctl_deploy.md
  - deploy demo: cli/squashctl_deploy_demo.md
  - deploy squash: cli/squashctl_deploy_squash.md
  - squash: cli/squashctl_squash.md
  - squash delete: cli/squashctl_squash_delete.md
  - squash status: cli/squashctl_squash_status.md
  - utils: cli/squashctl_utils.md
  - utils delete-attachments: cli/squashctl_utils_delete-attachments.md
  - utils delete-permissions: cli/squashctl_utils_delete-permissions.md
  - utils delete-planks: cli/squashctl_utils_delete-planks.md
  - utils list-attachments: cli/squashctl_utils_list-attachments.md
- Getting Started: getting-started.md
- Debuggers:
  - overview: debuggers.md
  - Java: debuggers/java.md
  - NodeJs: debuggers/nodejs.md
  - Python: debuggers/python_vscode.md
- Install:
  - Overview: install/README.md
  - Kubernetes: install/kubernetes.md
- IDEs: IDEs.md
site_author: solo.io
copyright: © Copyright 2018, solo.io Inc.
repo_url: https://github.com/solo-io/squash/
edit_uri: ""
google_analytics: ['UA-101654320-1', 'squash.solo.io'] # TODO (rick): UA-... copied from glooE
theme:
  name: 'mkdocs'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
  version: 0.1.1
plugins:
  - search


